// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDuIz05sKSX1fsHraV7iC9DmjTlu0bDbs',
    appId: '1:487198320569:web:54bee441e7cf99986bf868',
    messagingSenderId: '487198320569',
    projectId: 'lgbt-71666',
    authDomain: 'lgbt-71666.firebaseapp.com',
    storageBucket: 'lgbt-71666.firebasestorage.app',
    measurementId: 'G-GGXNFNST17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9IqY_eVodNgrku0UlSNLpWiBfosbFL0w',
    appId: '1:487198320569:android:788ebd1d798596986bf868',
    messagingSenderId: '487198320569',
    projectId: 'lgbt-71666',
    storageBucket: 'lgbt-71666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6LtBnelO0PBfuP_9X23bsLD8yKlJHs5A',
    appId: '1:487198320569:ios:ff2f2b4de35af3fa6bf868',
    messagingSenderId: '487198320569',
    projectId: 'lgbt-71666',
    storageBucket: 'lgbt-71666.firebasestorage.app',
    iosBundleId: 'com.example.lgbtTogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDuIz05sKSX1fsHraV7iC9DmjTlu0bDbs',
    appId: '1:487198320569:web:96365a6676a0343e6bf868',
    messagingSenderId: '487198320569',
    projectId: 'lgbt-71666',
    authDomain: 'lgbt-71666.firebaseapp.com',
    storageBucket: 'lgbt-71666.firebasestorage.app',
    measurementId: 'G-4GSQRS36FW',
  );
}
